WIP reading from websocket + redis
kkuprikov/easy-go pull request #1
Opened 2019-10-13 11:00 UTC by kkuprikov

2019-10-17 20:40 UTC, stamm requested changes

2019-10-17 20:40 UTC, stamm commented on wsgatherer/stat.go
> +func queueDict() func(string) string {
что-то ты здесь переусложнил, можно просто из статичной переменной  возвращать

2019-10-17 20:40 UTC, stamm commented on wsgatherer/jwt.go
> +func ParseJWT(tokenString string) []byte {
тут стоит возвращать ошибку ещё дополнительно, и обрабатывать выше

2019-10-17 20:40 UTC, stamm commented on wsgatherer/stat.go
> +	if conn, err := WsUpgrade(w, r); err == nil {
обычно в го стараются так писать, что упрощения и уплощения программы
```
if err != nil {
   return
}
other code
```

2019-10-17 20:40 UTC, stamm commented on wsgatherer/stat.go
> +func combineData(jwtoken string, input map[string]interface{}) map[string]interface{} {
а тут нет чёткой структуры? Лучше избегать пустых интерфейсов

2019-10-17 20:40 UTC, stamm commented on wsgatherer/stat.go
> +		fmt.Println(err)
Стоит её возвращать из функции, чтобы выше обрабатывать

2019-10-17 20:40 UTC, stamm commented on wsgatherer/stat.go
> +		fmt.Println("Type assertion failed: event is not a string", event)
Тоже стоит возвращать ошибку, ну или просто выходить из функции

2019-10-17 20:40 UTC, stamm commented on wsgatherer/stat.go
> +	msg, _ := json.Marshal(input)
не стоит игнорировать ошибки

2019-10-17 20:40 UTC, stamm commented on wsgatherer/runner.go
> +func WsUpgrade(w http.ResponseWriter, r *http.Request) (*websocket.Conn, error) {
Если функции больше нигде не нужны, то надо делать их неэкспортируемыми

2019-10-17 20:40 UTC, stamm commented on wsgatherer/stat.go
> +		var msg map[string]interface{}
Избегай пустых интерфейсов, они типо-небезопасные — очень часто могут приводить к ошибкам

2019-10-18 09:24 UTC, kkuprikov commented on wsgatherer/stat.go
> +func queueDict() func(string) string {
да, но тогда она будет глобальной, и будет ругаться линтер?)

2019-10-18 15:04 UTC, stamm commented on wsgatherer/stat.go
> +func queueDict() func(string) string {
да, это норм, можно игнорирование для конкретной переменной поставить

2019-10-18 19:08 UTC, stamm requested changes

2019-10-18 19:08 UTC, stamm commented on wsgatherer/jwt.go
> +			fmt.Println("JSON marshalling error: ", err)
лучше выходить явно с ошибкой, а ниже уже делать `return res, nil`

2019-10-18 19:08 UTC, stamm commented on wsgatherer/runner.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Не забывай выходить из функций, при ошибках

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +			params.Id = id
Лучше сразу делать 
```
params := params{
  ID: id,
  Count: count,
}

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +				done <- true
Вот тут не надо таких сложностей пока. Можно просто выйти из функции тут. А вообще лучше такое делать через контекст с функцией cancel. https://golang.org/pkg/context/#WithCancel

Ну если хочется использовать каналы, то ты можешь закрыть канал и тогда тоже сработает. Лучше ещё делать каналы, если через них сообщения не посылаются.
```
make(chan struct{})
done <- struct{}{}
```
Так не будет аллокаций лишних.
Но лучше вариант через контекст — его вообще надо везде прокидывать

2019-10-18 19:08 UTC, stamm commented on wsgatherer/redis.go
> +func redisPool() *redis.Pool {
Лучше вот так делать https://medium.com/statuscode/how-i-write-go-http-services-after-seven-years-37c208122831

2019-10-18 19:08 UTC, stamm commented on wsgatherer/jwt.go
> +		return res, err
Лучше явно указывать пустое значение, так будет понятней, когда читаешь код. И аллоцировать переменную res лучше как можно ближе к её заполнению, так будет меньше аллокаций, если будут ошибки

2019-10-18 19:08 UTC, stamm commented on wsgatherer/jwt.go
> +	if ok && token.Valid {
Лучше сделать обратную проверку и выйти

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +	ticker := time.NewTicker(period * time.Second)
Тикер надо не забывать останавливать, иначе будет память утекать
https://golang.org/pkg/time/#example_NewTicker

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +				deleteSpectator(id)
Ещё я думаю правильней будет удалять при выходе из этой функции. Например клиент просто закроет соединение, а мы выйдем из этой функции раньше (заиспользуем контекст, чтобы он закрывался при закрытии от клиента — это я хотел чуть попозже)

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +	var err error
Можно отдельно не инициировать переменную

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +	res, err := redis.String(conn.Do("GET", prefix+id))
Ошибку не хочешь обработать?

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +	var total = map[string]string{}
Если мы знаем сколько будет элементов в этой мапе, то лучше сразу сделать аллокацию на кол-во элементов
чуть ниже `make(map[string]string, len(keys))` Ну и алоцировать чуть пониже, когда ошибок нет)

2019-10-18 19:08 UTC, stamm commented on wsgatherer/spectators.go
> +	return json.Marshal(total)
Возможно мы хотим будем залогировать, если вдруг ошибка при маршалинге

2019-10-18 19:08 UTC, stamm commented on wsgatherer/stat.go
> +		fmt.Println("Could not read from redis", err)
Лучше делать первой обработку ошибки и выходить из функции, чтобы потом else не писать — это такой goway

2019-10-19 07:42 UTC, kkuprikov commented on wsgatherer/spectators.go
> +	res, err := redis.String(conn.Do("GET", prefix+id))
А я ж пробрасываю наверх
Или надо так?
```go
if err != nil {
		return nil, err
	}
	conn.Close()
	return res, nil
```

2019-10-20 08:46 UTC, stamm commented on cmd/main.go
> +	s := new(wsgatherer.Server)
Обычно пишут `s := &wsgatherer.Server{}`, `new` почти никогда не используют

2019-10-20 08:46 UTC, stamm commented on wsgatherer/redis.go
> +			c, err := redis.Dial("tcp", ":6379")
Нужно сделать, чтобы можно прокидывать адрес через параметр функции, чтобы не хардкодить

2019-10-20 08:46 UTC, stamm commented on wsgatherer/routes.go
> +func Routes(s *Server) {
Я бы вынес это в метод внутрь *Server

2019-10-20 08:46 UTC, stamm commented on wsgatherer/spectators.go
> +	res, err := redis.String(conn.Do("GET", prefix+id))
ага, так. Только `conn.Close()` у тебя не вызовется при ошибке, надо его в `defer` переместить

2019-10-20 09:19 UTC, stamm requested changes

2019-10-20 09:19 UTC, stamm commented on wsgatherer/stat.go
> +		go statReader(conn, params.ByName("jwt"), s.Db.Get())
Я не уверен, что надо вызывать в отдельной горутине

2019-10-20 09:19 UTC, stamm commented on wsgatherer/spectators.go
> +		go spectatorProcess(ws, params.ByName("id"), conn)
Я не уверен, что надо вызывать в отдельной горутине

2019-10-20 19:56 UTC, stamm requested changes

2019-10-20 19:56 UTC, stamm commented on wsgatherer/spectators.go
> +	for {
Тут тогда этот цикл не нужен будет

2019-10-20 19:56 UTC, stamm commented on wsgatherer/redis.go
> +func DoAndClose(pool *redis.Pool, command string, args ...interface{}) (reply interface{}, err error) {
Лучше не делать именнованные возвращаемые значения

2019-10-20 19:56 UTC, stamm commented on wsgatherer/redis.go
> +	res, err := conn.Do(command, args...)
для сокращения можно сделать
```
defer conn.Close()
return conn.Do(command, args...)
```

2019-10-21 09:27 UTC, kkuprikov commented on wsgatherer/redis.go
> +	res, err := conn.Do(command, args...)
Так линтер ругается
Error return value of `conn.Close` is not checked

2019-10-21 09:29 UTC, kkuprikov commented on wsgatherer/redis.go
> +	res, err := conn.Do(command, args...)
Но уже нашёл решение :)
https://stackoverflow.com/a/40398093/5276900

2019-10-21 15:53 UTC, stamm requested changes

2019-10-21 15:53 UTC, stamm commented on cmd/main.go
> +		return v, errEnvVarEmpty
лучше явно пустое значение возвращать

2019-10-21 15:53 UTC, stamm commented on cmd/main.go
> +		port = "6379"
лучше ещё поругаться, что порт левый какой-то указан

2019-10-21 15:53 UTC, stamm commented on wsgatherer/routes.go
> +func (s *Server) Routes() {
А давай переименуем в Start или Run?

2019-10-21 20:46 UTC, merged